name: Generate report

on:
  push:
    branches:
      - '**'
    paths:
      - 'p*/**'
  workflow_dispatch:

jobs:
  run:
    uses: XiPlus-Test/tps-actions-test/.github/workflows/generate-report.yml@main
