name: Get report

on:
  push:
    branches:
      - '**'
    paths:
      - 'p*/**'
  workflow_dispatch:

jobs:
  run:
    uses: TNFSH-Programming-Contest/tps-actions/.github/workflows/get-report.yml@report
    with:
      report-path: test.md
