name: Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "::notice title=Notice::test messages"

      - run: |
          echo "::warning title=Warning::test%0Amessages"

      - run: |
          echo "::error title=Error::test\nmessages"

      - run: |
          echo "1" >> test.txt
          echo "2" >> test.txt
          echo "3" >> test.txt
          msg=$(cat test.txt)
          echo "::error title=Error::$msg"
