name: Test
on:
  push:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Changes
        id: changes
        uses: TNFSH-Programming-Contest/tps-actions/.github/actions/get-changes@main

      - name: Dump
        run: |
          echo ${{ steps.changes.outputs.changes }}
