name: TPS verify

on:
  push:
    branches:
      - '**'
    paths:
      - 'p*/**'
  workflow_dispatch:
    inputs:
      target:
        description: 'Problem labels to verify'
        default: ''

jobs:
  run-push:
    if: github.event_name == 'push'
    uses: TNFSH-Programming-Contest/tps-actions/.github/workflows/tps-verify.yml@main

  run-dispatch:
    if: github.event_name == 'workflow_dispatch'
    uses: TNFSH-Programming-Contest/tps-actions/.github/workflows/tps-verify.yml@main
    with:
      problems: ${{ github.event.inputs.target }}
